version: '3'

services:
  zookeeper:
    image: ghcr.io/mailgun/dev/zookeeper:latest
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: ghcr.io/mailgun/dev/kafka:latest
    restart: always
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - ZOOKEEPER_IP=zookeeper
    ports:
      - "9092:9092"
